version: '3.0'
services:
  cooklyst-client:
    image: tubes-2-wbd-client:latest
    build: ./
    ports:
      - 5173:5173
    volumes:
      - './src:/usr/src/app/src'
      - './public:/usr/src/app/public'
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
